import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ELVINA
 */
public class kasir_1 extends javax.swing.JFrame {

    /**
     * Creates new form kasir_1
     */
    public kasir_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RBMA = new javax.swing.JRadioButton();
        RBMAB = new javax.swing.JRadioButton();
        RBBKR = new javax.swing.JRadioButton();
        RBBBS = new javax.swing.JRadioButton();
        RBBTS = new javax.swing.JRadioButton();
        RBBBK = new javax.swing.JRadioButton();
        RBBST = new javax.swing.JRadioButton();
        RBNGR = new javax.swing.JRadioButton();
        RBMGR = new javax.swing.JRadioButton();
        RBSAM = new javax.swing.JRadioButton();
        RBLLP = new javax.swing.JRadioButton();
        TxtMA = new javax.swing.JTextField();
        TxtMAB = new javax.swing.JTextField();
        TxtBKR = new javax.swing.JTextField();
        TxtBBS = new javax.swing.JTextField();
        TxtBTS = new javax.swing.JTextField();
        TxtBBK = new javax.swing.JTextField();
        TxtBST = new javax.swing.JTextField();
        TxtNGR = new javax.swing.JTextField();
        TxtMGR = new javax.swing.JTextField();
        TxtSAM = new javax.swing.JTextField();
        TxtLLP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxtjmlMA = new javax.swing.JTextField();
        TxtjmlMAB = new javax.swing.JTextField();
        TxtjmlBKR = new javax.swing.JTextField();
        TxtjmlBBS = new javax.swing.JTextField();
        TxtjmlBTS = new javax.swing.JTextField();
        TxtjmlBBK = new javax.swing.JTextField();
        TxtjmlBST = new javax.swing.JTextField();
        TxtjmlNGR = new javax.swing.JTextField();
        TxtjmlMGR = new javax.swing.JTextField();
        TxtjmlSAM = new javax.swing.JTextField();
        TxtjmlLLP = new javax.swing.JTextField();
        RBTEH = new javax.swing.JRadioButton();
        RBKOP = new javax.swing.JRadioButton();
        RBLMT = new javax.swing.JRadioButton();
        RBNTS = new javax.swing.JRadioButton();
        RBEXR = new javax.swing.JRadioButton();
        RBBLT = new javax.swing.JRadioButton();
        RBKRP = new javax.swing.JRadioButton();
        RBBKW = new javax.swing.JRadioButton();
        RBPGM = new javax.swing.JRadioButton();
        RBPST = new javax.swing.JRadioButton();
        TxtTEH = new javax.swing.JTextField();
        TxtKOP = new javax.swing.JTextField();
        TxtLMT = new javax.swing.JTextField();
        TxtNTS = new javax.swing.JTextField();
        TxtEXR = new javax.swing.JTextField();
        TxtBLT = new javax.swing.JTextField();
        TxtKRP = new javax.swing.JTextField();
        TxtBKW = new javax.swing.JTextField();
        TxtPGM = new javax.swing.JTextField();
        TxtPST = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TxtjmlTEH = new javax.swing.JTextField();
        TxtjmlKOP = new javax.swing.JTextField();
        TxtjmlLMT = new javax.swing.JTextField();
        TxtjmlNTS = new javax.swing.JTextField();
        TxtjmlEXR = new javax.swing.JTextField();
        TxtjmlBLT = new javax.swing.JTextField();
        TxtjmlKRP = new javax.swing.JTextField();
        TxtjmlBKW = new javax.swing.JTextField();
        TxtjmlPGM = new javax.swing.JTextField();
        TxtjmlPST = new javax.swing.JTextField();
        BtnHitung = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        TxtjmlHarga = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel1.setText("KASIR RUMAH MAKAN MAS TEGAR");

        RBMA.setText("MIE AYAM");
        RBMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMAActionPerformed(evt);
            }
        });

        RBMAB.setText("MIE AYAM BAKSO");
        RBMAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMABActionPerformed(evt);
            }
        });

        RBBKR.setText("BAKSO KERIKIL");
        RBBKR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBKRActionPerformed(evt);
            }
        });

        RBBBS.setText("BAKSO BIASA");
        RBBBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBBSActionPerformed(evt);
            }
        });

        RBBTS.setText("BAKSO TENES");
        RBBTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBTSActionPerformed(evt);
            }
        });

        RBBBK.setText("BAKSO BERANAK");
        RBBBK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBBKActionPerformed(evt);
            }
        });

        RBBST.setText("BAKSO SETAN");
        RBBST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBSTActionPerformed(evt);
            }
        });

        RBNGR.setText("NASI GORENG");
        RBNGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBNGRActionPerformed(evt);
            }
        });

        RBMGR.setText("MIE GORENG");
        RBMGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMGRActionPerformed(evt);
            }
        });

        RBSAM.setText("SOTO AYAM");
        RBSAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSAMActionPerformed(evt);
            }
        });

        RBLLP.setText("LALAPAN");
        RBLLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBLLPActionPerformed(evt);
            }
        });

        TxtMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMAActionPerformed(evt);
            }
        });

        TxtNGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNGRActionPerformed(evt);
            }
        });

        TxtLLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLLPActionPerformed(evt);
            }
        });

        jLabel2.setText("X");

        jLabel3.setText("X");

        jLabel4.setText("X");

        jLabel5.setText("X");

        jLabel6.setText("X");

        jLabel7.setText("X");

        jLabel8.setText("X");

        jLabel9.setText("X");

        jLabel10.setText("X");

        jLabel11.setText("X");

        jLabel12.setText("X");

        TxtjmlMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtjmlMAActionPerformed(evt);
            }
        });

        TxtjmlMAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtjmlMABActionPerformed(evt);
            }
        });

        TxtjmlMGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtjmlMGRActionPerformed(evt);
            }
        });

        RBTEH.setText("TEH");
        RBTEH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTEHActionPerformed(evt);
            }
        });

        RBKOP.setText("KOPI");
        RBKOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBKOPActionPerformed(evt);
            }
        });

        RBLMT.setText("LEMON TEA");
        RBLMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBLMTActionPerformed(evt);
            }
        });

        RBNTS.setText("NUTRISARI");
        RBNTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBNTSActionPerformed(evt);
            }
        });

        RBEXR.setText("EXTRAJOSS");
        RBEXR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEXRActionPerformed(evt);
            }
        });

        RBBLT.setText("BUBBLE TEA");
        RBBLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBLTActionPerformed(evt);
            }
        });

        RBKRP.setText("KERUPUK PANGSIT");
        RBKRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBKRPActionPerformed(evt);
            }
        });

        RBBKW.setText("BAKWAN");
        RBBKW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBKWActionPerformed(evt);
            }
        });

        RBPGM.setText("PENTOL GORENG MAYO");
        RBPGM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPGMActionPerformed(evt);
            }
        });

        RBPST.setText("PENTOL SETAN");
        RBPST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPSTActionPerformed(evt);
            }
        });

        TxtKOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKOPActionPerformed(evt);
            }
        });

        jLabel13.setText("X");

        jLabel14.setText("X");

        jLabel15.setText("X");

        jLabel16.setText("X");

        jLabel17.setText("X");

        jLabel18.setText("X");

        jLabel19.setText("X");

        jLabel20.setText("X");

        jLabel21.setText("X");

        jLabel22.setText("X");

        TxtjmlNTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtjmlNTSActionPerformed(evt);
            }
        });

        TxtjmlPGM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtjmlPGMActionPerformed(evt);
            }
        });

        BtnHitung.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnHitung.setText("HITUNG");
        BtnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHitungActionPerformed(evt);
            }
        });

        BtnHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnExit.setText("EXIT");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("HARGA");

        jMenu1.setText("File");

        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBMA)
                    .addComponent(RBMAB)
                    .addComponent(RBBKR)
                    .addComponent(RBBBS)
                    .addComponent(RBBTS)
                    .addComponent(RBBBK)
                    .addComponent(RBBST)
                    .addComponent(RBNGR)
                    .addComponent(RBMGR)
                    .addComponent(RBSAM)
                    .addComponent(RBLLP))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtBBS)
                    .addComponent(TxtBTS)
                    .addComponent(TxtBBK)
                    .addComponent(TxtBST)
                    .addComponent(TxtNGR)
                    .addComponent(TxtMGR)
                    .addComponent(TxtSAM)
                    .addComponent(TxtLLP)
                    .addComponent(TxtMA, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(TxtMAB)
                    .addComponent(TxtBKR))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtjmlMAB)
                    .addComponent(TxtjmlBKR)
                    .addComponent(TxtjmlBBS)
                    .addComponent(TxtjmlBTS)
                    .addComponent(TxtjmlBBK)
                    .addComponent(TxtjmlBST)
                    .addComponent(TxtjmlNGR)
                    .addComponent(TxtjmlMGR)
                    .addComponent(TxtjmlSAM)
                    .addComponent(TxtjmlLLP)
                    .addComponent(TxtjmlMA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(TxtjmlHarga))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(RBTEH)
                                                        .addComponent(RBKOP)
                                                        .addComponent(RBLMT))
                                                    .addGap(77, 77, 77)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(TxtTEH)
                                                        .addComponent(TxtKOP)
                                                        .addComponent(TxtLMT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(RBNTS)
                                                    .addGap(77, 77, 77)
                                                    .addComponent(TxtNTS))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(RBEXR)
                                                    .addGap(75, 75, 75)
                                                    .addComponent(TxtEXR))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(RBBLT)
                                                    .addGap(75, 75, 75)
                                                    .addComponent(TxtBLT))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(RBKRP)
                                                        .addComponent(RBBKW))
                                                    .addGap(41, 41, 41)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TxtKRP)
                                                        .addComponent(TxtBKW, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(RBPST)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(TxtPST, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(RBPGM)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(TxtPGM, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlTEH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlKOP))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlLMT))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlNTS))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlEXR))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlBLT))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlKRP))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlBKW))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlPGM))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtjmlPST, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(BtnHitung))
                                .addGap(18, 18, 18)
                                .addComponent(BtnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(BtnExit)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBMA)
                    .addComponent(TxtMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtjmlMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBTEH)
                    .addComponent(TxtTEH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(TxtjmlTEH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBMAB)
                    .addComponent(TxtMAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TxtjmlMAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBKOP)
                    .addComponent(TxtKOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(TxtjmlKOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBKR)
                    .addComponent(TxtBKR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TxtjmlBKR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBLMT)
                    .addComponent(TxtLMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TxtjmlLMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBBS)
                    .addComponent(TxtBBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TxtjmlBBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBNTS)
                    .addComponent(TxtNTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(TxtjmlNTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBTS)
                    .addComponent(TxtBTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TxtjmlBTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBEXR)
                    .addComponent(TxtEXR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(TxtjmlEXR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBBK)
                    .addComponent(TxtBBK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxtjmlBBK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBBLT)
                    .addComponent(TxtBLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(TxtjmlBLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBST)
                    .addComponent(TxtBST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(TxtjmlBST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBKRP)
                    .addComponent(TxtKRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(TxtjmlKRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBNGR)
                    .addComponent(TxtNGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TxtjmlNGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBBKW)
                    .addComponent(TxtBKW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(TxtjmlBKW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBMGR)
                    .addComponent(TxtMGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(TxtjmlMGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBPGM)
                    .addComponent(TxtPGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(TxtjmlPGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBSAM)
                    .addComponent(TxtSAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(TxtjmlSAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBPST)
                    .addComponent(TxtPST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(TxtjmlPST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBLLP)
                    .addComponent(TxtLLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(TxtjmlLLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnHitung)
                    .addComponent(BtnHapus)
                    .addComponent(BtnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(TxtjmlHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMAActionPerformed
        int mieayam = 15000;
        if (RBMA.isSelected()) {
            TxtMA.setText("" + RBMA.getText());
            TxtMA.setText("" + mieayam);
        } else {
            TxtMA.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_RBMAActionPerformed

    private void RBBKRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBKRActionPerformed
        int baksokerikil = 15000;
        if (RBBKR.isSelected()) {
            TxtBKR.setText("" + RBBKR.getText());
            TxtBKR.setText("" + baksokerikil);
        } else {
            TxtBKR.setText("");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_RBBKRActionPerformed

    private void TxtMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMAActionPerformed

    private void TxtNGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNGRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNGRActionPerformed

    private void TxtLLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLLPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLLPActionPerformed

    private void TxtjmlMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtjmlMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtjmlMAActionPerformed

    private void TxtjmlMABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtjmlMABActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtjmlMABActionPerformed

    private void TxtjmlMGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtjmlMGRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtjmlMGRActionPerformed

    private void RBTEHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTEHActionPerformed
        int teh = 5000;
        if (RBTEH.isSelected()) {
            TxtTEH.setText("" + RBTEH.getText());
            TxtTEH.setText("" + teh);
        } else {
            TxtTEH.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBTEHActionPerformed

    private void RBKOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBKOPActionPerformed
        int kopi = 5000;
        if (RBKOP.isSelected()) {
            TxtKOP.setText("" + RBKOP.getText());
            TxtKOP.setText("" + kopi);
        } else {
            TxtKOP.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBKOPActionPerformed

    private void RBLMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBLMTActionPerformed
        int lemontea = 5000;
        if (RBLMT.isSelected()) {
            TxtLMT.setText("" + RBLMT.getText());
            TxtLMT.setText("" + lemontea);
        } else {
            TxtLMT.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBLMTActionPerformed

    private void RBNTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBNTSActionPerformed
        int nutrisari = 5000;
        if (RBNTS.isSelected()) {
            TxtNTS.setText("" + RBNTS.getText());
            TxtNTS.setText("" + nutrisari);
        } else {
            TxtNTS.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBNTSActionPerformed

    private void RBBLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBLTActionPerformed
        int bubbletea = 10000;
        if (RBBLT.isSelected()) {
            TxtBLT.setText("" + RBBLT.getText());
            TxtBLT.setText("" + bubbletea);
        } else {
            TxtBLT.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_RBBLTActionPerformed

    private void RBBKWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBKWActionPerformed
        int bakwan = 5000;
        if (RBBKW.isSelected()) {
            TxtBKW.setText("" + RBBKW.getName());
            TxtBKW.setText("" + bakwan);
        } else {
            TxtBKW.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBBKWActionPerformed

    private void TxtKOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKOPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKOPActionPerformed

    private void TxtjmlNTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtjmlNTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtjmlNTSActionPerformed

    private void TxtjmlPGMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtjmlPGMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtjmlPGMActionPerformed

    private void RBMABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMABActionPerformed
        int mieayambakso = 20000;
        if (RBMAB.isSelected()) {
            TxtMAB.setText("" + RBMAB.getText());
            TxtMAB.setText("" + mieayambakso);
        } else {
            TxtMAB.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_RBMABActionPerformed

    private void RBBBKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBBKActionPerformed
        int baksoberanak = 25000;
        if (RBBBK.isSelected()) {
            TxtBBK.setText("" + RBBBK.getText());
            TxtBBK.setText("" + baksoberanak);
        } else {
            TxtBBK.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBBBKActionPerformed

    private void RBBBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBBSActionPerformed
        int baksobiasa = 15000;
        if (RBBBS.isSelected()) {
            TxtBBS.setText("" + RBBBS.getText());
            TxtBBS.setText("" + baksobiasa);
        } else {
            TxtBBS.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBBBSActionPerformed

    private void RBBTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBTSActionPerformed
        int baksotenes = 25000;
        if (RBBTS.isSelected()) {
            TxtBTS.setText("" + RBBTS.getText());
            TxtBTS.setText("" + baksotenes);
        } else {
            TxtBTS.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_RBBTSActionPerformed

    private void RBBSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBSTActionPerformed
        int baksosetan = 25000;
        if (RBBST.isSelected()) {
            TxtBST.setText("" + RBBST.getText());
            TxtBST.setText("" + baksosetan);
        } else {
            TxtBST.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBBSTActionPerformed

    private void RBNGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBNGRActionPerformed
        int nasigoreng = 20000;
        if (RBNGR.isSelected()) {
            TxtNGR.setText("" + RBNGR.getText());
            TxtNGR.setText("" + nasigoreng);
        } else {
            TxtNGR.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_RBNGRActionPerformed

    private void RBMGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMGRActionPerformed
        int miegoreng = 20000;
        if (RBMGR.isSelected()) {
            TxtMGR.setText("" + RBMGR.getText());
            TxtMGR.setText("" + miegoreng);
        } else {
            TxtMGR.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBMGRActionPerformed

    private void RBSAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSAMActionPerformed
        int sotoayam = 20000;
        if (RBSAM.isSelected()) {
            TxtSAM.setText("" + RBSAM.getText());
            TxtSAM.setText("" + sotoayam);
        } else {
            TxtSAM.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBSAMActionPerformed

    private void RBLLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBLLPActionPerformed
        int lalapan = 25000;
        if (RBLLP.isSelected()) {
            TxtLLP.setText("" + RBLLP.getText());
            TxtLLP.setText("" + lalapan);
        } else {
            TxtLLP.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_RBLLPActionPerformed

    private void RBEXRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEXRActionPerformed
        int extrajoss = 5000;
        if (RBEXR.isSelected()) {
            TxtEXR.setText("" + RBEXR.getText());
            TxtEXR.setText("" + extrajoss);
        } else {
            TxtEXR.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_RBEXRActionPerformed

    private void RBKRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBKRPActionPerformed
        int kerupukpangsit = 5000;
        if (RBKRP.isSelected()) {
            TxtKRP.setText("" + RBKRP.getText());
            TxtKRP.setText("" + kerupukpangsit);
        } else {
            TxtKRP.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_RBKRPActionPerformed

    private void RBPGMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPGMActionPerformed
        int pentolgorengmayo = 15000;
        if (RBPGM.isSelected()) {
            TxtPGM.setText("" + RBPGM.getText());
            TxtPGM.setText("" + pentolgorengmayo);
        } else {
            TxtPGM.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_RBPGMActionPerformed

    private void RBPSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPSTActionPerformed
        int pentolsetan = 15000;
        if (RBPST.isSelected()) {
            TxtPST.setText("" + RBPST.getText());
            TxtPST.setText("" + pentolsetan);
        } else {
            TxtPST.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_RBPSTActionPerformed

    private void BtnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHitungActionPerformed
        int total = 0;

        if (RBMA.isSelected()) {
            String MA = TxtjmlMA.getText();
            int jmlMA = Integer.parseInt(MA);
            int HargaMA = jmlMA * 15000;
            total = total + HargaMA;
        }
        if (RBMAB.isSelected()) {
            String MAB = TxtjmlMAB.getText();
            int jmlMAB = Integer.parseInt(MAB);
            int HargaMAB = jmlMAB * 20000;
            total = total + HargaMAB;
        }
        if (RBBKR.isSelected()) {
            String BKR = TxtjmlBKR.getText();
            int jmlBKR = Integer.parseInt(BKR);
            int HargaBKR = jmlBKR * 15000;
            total = total + HargaBKR;
        }
        if (RBBBS.isSelected()) {
            String BBS = TxtjmlBBS.getText();
            int jmlBBS = Integer.parseInt(BBS);
            int HargaBBS = jmlBBS * 15000;
            total = total + HargaBBS;
        }
        if (RBBTS.isSelected()) {
            String BTS = TxtjmlBTS.getText();
            int jmlBTS = Integer.parseInt(BTS);
            int HargaBTS = jmlBTS * 25000;
            total = total + HargaBTS;
        }
        if (RBBBK.isSelected()) {
            String BBK = TxtjmlBBK.getText();
            int jmlBBK = Integer.parseInt(BBK);
            int HargaBBK = jmlBBK * 25000;
            total = total + HargaBBK;
        }
        if (RBBST.isSelected()) {
            String BST = TxtjmlBST.getText();
            int jmlBST = Integer.parseInt(BST);
            int HargaBST = jmlBST * 25000;
            total = total + HargaBST;
        }
        if (RBNGR.isSelected()) {
            String NGR = TxtjmlNGR.getText();
            int jmlNGR = Integer.parseInt(NGR);
            int HargaNGR = jmlNGR * 20000;
            total = total + HargaNGR;
        }
        if (RBMGR.isSelected()) {
            String MGR = TxtjmlMGR.getText();
            int jmlMGR = Integer.parseInt(MGR);
            int HargaMGR = jmlMGR * 20000;
            total = total + HargaMGR;
        }
        if (RBSAM.isSelected()) {
            String SAM = TxtjmlSAM.getText();
            int jmlSAM = Integer.parseInt(SAM);
            int HargaSAM = jmlSAM * 20000;
            total = total + HargaSAM;
        }
        if (RBLLP.isSelected()) {
            String LLP = TxtjmlLLP.getText();
            int jmlLLP = Integer.parseInt(LLP);
            int HargaLLP = jmlLLP * 25000;
            total = total + HargaLLP;
        }
        if (RBTEH.isSelected()) {
            String TEH = TxtjmlTEH.getText();
            int jmlTEH = Integer.parseInt(TEH);
            int HargaTEH = jmlTEH * 5000;
            total = total + HargaTEH;
        }
        if (RBKOP.isSelected()) {
            String KOP = TxtjmlKOP.getText();
            int jmlKOP = Integer.parseInt(KOP);
            int HargaKOP = jmlKOP * 5000;
            total = total + HargaKOP;
        }
        if (RBLMT.isSelected()) {
            String LMT = TxtjmlLMT.getText();
            int jmlLMT = Integer.parseInt(LMT);
            int HargaLMT = jmlLMT * 5000;
            total = total + HargaLMT;
        }
        if (RBNTS.isSelected()) {
            String NTS = TxtjmlNTS.getText();
            int jmlNTS = Integer.parseInt(NTS);
            int HargaNTS = jmlNTS * 5000;
            total = total + HargaNTS;
        }
        if (RBEXR.isSelected()) {
            String EXR = TxtjmlEXR.getText();
            int jmlEXR = Integer.parseInt(EXR);
            int HargaEXR = jmlEXR * 5000;
            total = total + HargaEXR;
        }
        if (RBBLT.isSelected()) {
            String BLT = TxtjmlBLT.getText();
            int jmlBLT = Integer.parseInt(BLT);
            int HargaBLT = jmlBLT * 10000;
            total = total + HargaBLT;
        }
        if (RBKRP.isSelected()) {
            String KRP = TxtjmlKRP.getText();
            int jmlKRP = Integer.parseInt(KRP);
            int HargaKRP = jmlKRP * 5000;
            total = total + HargaKRP;
        }
        if (RBBKW.isSelected()) {
            String BKW = TxtjmlBKW.getText();
            int jmlBKW = Integer.parseInt(BKW);
            int HargaBKW = jmlBKW * 5000;
            total = total + HargaBKW;
        }
        if (RBPGM.isSelected()) {
            String PGM = TxtjmlPGM.getText();
            int jmlPGM = Integer.parseInt(PGM);
            int HargaPGM = jmlPGM * 15000;
            total = total + HargaPGM;
        }
        if (RBPST.isSelected()) {
            String PST = TxtjmlPST.getText();
            int jmlPST = Integer.parseInt(PST);
            int HargaPST = jmlPST * 5000;
            total = total + HargaPST;;
        }
        TxtjmlHarga.setText("" + total);
// TODO add your handling code here:
    }//GEN-LAST:event_BtnHitungActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        TxtjmlMA.setEditable(false);
        TxtjmlMA.setText("");
        TxtjmlMAB.setEditable(false);
        TxtjmlMAB.setText("");
        TxtjmlBKR.setEditable(false);
        TxtjmlBKR.setText("");
        TxtjmlBBS.setEditable(false);
        TxtjmlBBS.setText("");
        TxtjmlBTS.setEditable(false);
        TxtjmlBTS.setText("");
        TxtjmlBBK.setEditable(false);
        TxtjmlBBK.setText("");
        TxtjmlBST.setEditable(false);
        TxtjmlBST.setText("");
        TxtjmlNGR.setEditable(false);
        TxtjmlNGR.setText("");
        TxtjmlMGR.setEditable(false);
        TxtjmlMGR.setText("");
        TxtjmlSAM.setEditable(false);
        TxtjmlSAM.setText("");
        TxtjmlLLP.setEditable(false);
        TxtjmlLLP.setText("");
        TxtjmlTEH.setEditable(false);
        TxtjmlTEH.setText("");
        TxtjmlKOP.setEditable(false);
        TxtjmlKOP.setText("");
        TxtjmlLMT.setEditable(false);
        TxtjmlLMT.setText("");
        TxtjmlNTS.setEditable(false);
        TxtjmlNTS.setText("");
        TxtjmlEXR.setEditable(false);
        TxtjmlEXR.setText("");
        TxtjmlBLT.setEditable(false);
        TxtjmlBLT.setText("");
        TxtjmlKRP.setEditable(false);
        TxtjmlKRP.setText("");
        TxtjmlBKW.setEditable(false);
        TxtjmlBKW.setText("");
        TxtjmlPGM.setEditable(false);
        TxtjmlPGM.setText("");
        TxtjmlPST.setEditable(false);
        TxtjmlPST.setText("");
        TxtjmlHarga.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        int X = JOptionPane.showConfirmDialog(null, "Keluar Program", "Exit",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (X == JOptionPane.YES_OPTION) {
            System.exit(0);
            dispose();
        }
    }//GEN-LAST:event_BtnExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnHitung;
    private javax.swing.JRadioButton RBBBK;
    private javax.swing.JRadioButton RBBBS;
    private javax.swing.JRadioButton RBBKR;
    private javax.swing.JRadioButton RBBKW;
    private javax.swing.JRadioButton RBBLT;
    private javax.swing.JRadioButton RBBST;
    private javax.swing.JRadioButton RBBTS;
    private javax.swing.JRadioButton RBEXR;
    private javax.swing.JRadioButton RBKOP;
    private javax.swing.JRadioButton RBKRP;
    private javax.swing.JRadioButton RBLLP;
    private javax.swing.JRadioButton RBLMT;
    private javax.swing.JRadioButton RBMA;
    private javax.swing.JRadioButton RBMAB;
    private javax.swing.JRadioButton RBMGR;
    private javax.swing.JRadioButton RBNGR;
    private javax.swing.JRadioButton RBNTS;
    private javax.swing.JRadioButton RBPGM;
    private javax.swing.JRadioButton RBPST;
    private javax.swing.JRadioButton RBSAM;
    private javax.swing.JRadioButton RBTEH;
    private javax.swing.JTextField TxtBBK;
    private javax.swing.JTextField TxtBBS;
    private javax.swing.JTextField TxtBKR;
    private javax.swing.JTextField TxtBKW;
    private javax.swing.JTextField TxtBLT;
    private javax.swing.JTextField TxtBST;
    private javax.swing.JTextField TxtBTS;
    private javax.swing.JTextField TxtEXR;
    private javax.swing.JTextField TxtKOP;
    private javax.swing.JTextField TxtKRP;
    private javax.swing.JTextField TxtLLP;
    private javax.swing.JTextField TxtLMT;
    private javax.swing.JTextField TxtMA;
    private javax.swing.JTextField TxtMAB;
    private javax.swing.JTextField TxtMGR;
    private javax.swing.JTextField TxtNGR;
    private javax.swing.JTextField TxtNTS;
    private javax.swing.JTextField TxtPGM;
    private javax.swing.JTextField TxtPST;
    private javax.swing.JTextField TxtSAM;
    private javax.swing.JTextField TxtTEH;
    private javax.swing.JTextField TxtjmlBBK;
    private javax.swing.JTextField TxtjmlBBS;
    private javax.swing.JTextField TxtjmlBKR;
    private javax.swing.JTextField TxtjmlBKW;
    private javax.swing.JTextField TxtjmlBLT;
    private javax.swing.JTextField TxtjmlBST;
    private javax.swing.JTextField TxtjmlBTS;
    private javax.swing.JTextField TxtjmlEXR;
    private javax.swing.JTextField TxtjmlHarga;
    private javax.swing.JTextField TxtjmlKOP;
    private javax.swing.JTextField TxtjmlKRP;
    private javax.swing.JTextField TxtjmlLLP;
    private javax.swing.JTextField TxtjmlLMT;
    private javax.swing.JTextField TxtjmlMA;
    private javax.swing.JTextField TxtjmlMAB;
    private javax.swing.JTextField TxtjmlMGR;
    private javax.swing.JTextField TxtjmlNGR;
    private javax.swing.JTextField TxtjmlNTS;
    private javax.swing.JTextField TxtjmlPGM;
    private javax.swing.JTextField TxtjmlPST;
    private javax.swing.JTextField TxtjmlSAM;
    private javax.swing.JTextField TxtjmlTEH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    private String mieayam() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String mieayambakso() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String baksokerikil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
